on:
  push:
    branches: [ master ]
    paths:
      - 'applications/app1/**'
      - 'applications/app2/**'

jobs:
  build-python:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && contains(github.event.head_commit.modified, 'applications/app2/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          cd applications/app2
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest

  build-javascript:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && contains(github.event.head_commit.modified, 'applications/app1/')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd applications/app1
          npm install
      - name: Run tests
        run: npm test



# on:
#   push:
#     branches: [ master ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
#     - name: Install dependencies
#       run: |
#         cd applications/app2
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         pip install pytest
#     - name: Run tests
#       run: pytest
