name: Semantic Release for Apps

on:
  push:
    branches:
      - master
    paths:
      - 'applications/**'

permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0

      # Get the name of the directory that was changed
      APP_NAME=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | awk -F/ '{print $2}' | sort -u)

      # Update the tag format to include the name of the directory
      TAG_FORMAT="${APP_NAME}-v${{ steps.semantic.outputs.release-version }}"

      # Update the version number in the CHANGELOG.md file
      sed -i -E "s/${APP_NAME}-v[0-9]+\.[0-9]+\.[0-9]+/${TAG_FORMAT}/" CHANGELOG.md
        continue-on-error: true 

      # https://github.com/marketplace/actions/semantic-release-action#usage
      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        with:
          tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
          additional_packages: |
            ['@semantic-release/changelog', '@semantic-release/git']
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG', tagPrefix : 'app1-v'}], '@semantic-release/github', '@semantic-release/git']
          # specify default branches to add support for the `main` branch
          # which semantic-release doesn't have as a default yet.
          branches: |
            [
              'master'
            ]

      # # Get the latest version tag
      # - name: Get latest version tag
      #   run: |
      #     version=$(git describe --tags --abbrev=0)
      #     echo "::set-output name=version::$version"

      - name: Semantic Release Output Summary
        id: semantic_summary
        run: |
          echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

