name: Semantic Release for Apps
on:
  push:
    branches:
      - master
    paths:
      - 'applications/**'



permissions: write-all



jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ['app1', 'app2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout
        with:
          fetch-depth: 0
      - name: Update tag format
        id: update_tag_format
        run: |
          APP_NAME=${{ matrix.app_name }}
          echo "::set-output name=tag_format::${APP_NAME}-v\${{ steps.version.outputs.version }}"
      - name: Get version
        id: get_version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git fetch --prune --unshallow --tags
          git checkout "${{ github.sha }}"
          version=$(npx -p semantic-release@17 -p @semantic-release/git -c 'echo {}' | npx -p semantic-release@17 -p @semantic-release/git -s)
          echo "::set-output name=version::$version"
        continue-on-error: true
      - name: Add new version to changelog
        id: add_version_to_changelog
        run: |
          version=${{ steps.get_version.outputs.version }}
          sed -i "s/\[[0-9]\+\.[0-9]\+\.[0-9]\+\]/[${version}] $(date +'%Y-%m-%d')/" applications/${{ matrix.app_name }}/CHANGELOG.md
        continue-on-error: true
      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB2 }}
        with:
          tag_format: '${{ steps.update_tag_format.outputs.tag_format }}'
          additional_packages: |
            ['@semantic-release/changelog', '@semantic-release/git']
          plugins: |
            [              '@semantic-release/commit-analyzer',              '@semantic-release/release-notes-generator',              ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG'}],
              '@semantic-release/github',
              ['@semantic-release/git', {                assets: ['applications/${{ matrix.app_name }}/CHANGELOG.md'],
                message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}\n\nSigned-off-by: Thejaswiiii <abc@gmail.com>'
              }]
            ]
          branches: |
            [              'master'            ]
        continue-on-error: true
      - name: Semantic Release Output Summary
        id: semantic_summary
        run: |
          echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        continue-on-error: true