name: Semantic Release for App1

on:
  push:
    branches:
      - master
    paths:
      - 'applications/app1/**'

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.ref }}
        #   fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd applications/app1
          npm install

      - name: Semantic Release
        uses: docker://ghcr.io/codfish/semantic-release-action:v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          tag_format: 'v${version}'
          additional_packages: |
            ['@semantic-release/changelog', '@semantic-release/git', '@semantic-release/npm']
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG'}], '@semantic-release/github', '@semantic-release/git']
          # specify default branches to add support for the `main` branch
          # which semantic-release doesn't have as a default yet.
          branches: |
            [
              'master'
            ]
          cwd: applications/app1



# ---
# name: Continuous Delivery

# on:
#   push:
#     branches: 
#         - master

# paths:
#       - 'applications/app1/**'


# jobs:
#   release:
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       # https://github.com/marketplace/actions/semantic-release-action#usage
#       - name: Semantic Release
#         uses: docker://ghcr.io/codfish/semantic-release-action:v2
#         id: semantic
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
#         with:
#           tag_format: 'v${version}'
#           additional_packages: |
#             ['@semantic-release/changelog', '@semantic-release/git']
#           plugins: |
#             ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', ['@semantic-release/changelog', {changelogTitle: '# CHANGELOG'}], '@semantic-release/github', '@semantic-release/git']
#           # specify default branches to add support for the `main` branch
#           # which semantic-release doesn't have as a default yet.
#           branches: |
#             [
#               'master'
#             ]
#       - name: Semantic Release Output Summary
#         id: semantic_summary
#         run: |
#           echo "### Semantic Version = ${{ steps.semantic.outputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
#           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
#           echo "${{ toJson(steps.semantic.outputs) }}" >> $GITHUB_STEP_SUMMARY
#           echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
#         continue-on-error: true

#       # - run: echo ${{ steps.semantic.outputs.release-version }}

#       # - run: echo "$OUTPUTS"
#       #   env:
#       #     OUTPUTS: ${{ toJson(steps.semantic.outputs) }}

#       # - uses: codfish/some-other-action@v1
#       #   with:
#       #     release-version: ${{ steps.semantic.outputs.release-version }}

#       # - name: docker push version
#       #   if: steps.semantic.outputs.new-release-published == 'true'
#       #   run: |
#       #     docker tag some-image some-image:$TAG
#       #     docker push some-image:$TAG
#       #   env:
#       #     TAG: v$RELEASE_VERSION